name: Deploy to Firebase Hosting on PR

on: 
  workflow_call:
      inputs:
        channel:
          type: string
          required: true
      secrets:
        BACKEND_URL:
          required: true
        FIREBASE_SERVICE_ACCOUNT_GH_ENVS_2022:
          required: true

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependecies
        run: npm ci 
      
      - name: Build project
        run: npm run build
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GH_ENVS_2022 }}'
          projectId: gh-envs-2022
          channelId: ${{ inputs.channel }}
