name: Deploy to Firebase Hosting on PR

on: 
  push:
    branches: [live, staging, development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref_name }}
      url: ${{ steps.firebase_deploy.outputs.details_url }}
    env:
      PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependecies
        run: npm ci 
      
      - name: Build project
        run: npm run build
      
      - name: Deploy to Firebase
        id: firebase_deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GH_ENVS_2022 }}'
          projectId: gh-envs-2022
          channelId: ${{ github.ref_name }}
